http:
  routers:
    traefik:
      rule: "Host(`traefik.traefik.me`)"
      service: "api@internal"
      tls:
        domains:
          - main: "traefik.me"
            sans:
              - "*.traefik.me"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/cert.pem
        keyFile: /etc/ssl/traefik/privkey.pem
  certificates:
    - certFile: /etc/ssl/traefik/cert.pem
      keyFile: /etc/ssl/traefik/privkey.pem
