version: '3.5'

services:
  rabbitmq:
    restart: unless-stopped
    container_name: rabbitmq_setup
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - traefik
      - service
    ports:
      - "25672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.traefik.me`)"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  maildev:
    restart: unless-stopped
    container_name: maildev_setup
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
      - traefik
      - service
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.maildev.rule=Host(`maildev.traefik.me`)"
      - "traefik.http.routers.maildev.tls=true"
      - "traefik.http.services.maildev.loadbalancer.server.port=80"

  traefik:
    image: traefik:2.8.1
    container_name: traefik_setup
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.deployment/docker/containers/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./.deployment/docker/containers/traefik/config.yml:/etc/traefik/config.yml:ro
      - certs:/etc/ssl/traefik
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

  reverse-proxy-https-helper:
    container_name: reverse_proxy_setup
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
    networks:
      - traefik
      - service

volumes:
  rabbitmq_volume: {}
  certs: {}

networks:
  service:
    name: service
  traefik:
    name: traefik