version: '3.5'

services:
  rabbitmq:
    restart: unless-stopped
    container_name: setup_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - service
    ports:
      - 25673:5672
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit

  maildev:
    restart: unless-stopped
    container_name: setup_maildev
    image: maildev/maildev
    ports:
      - 1080:80
      - 1025:25
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
      - service

volumes:
  rabbitmq_volume: {}
  certs: {}

networks:
  service:
    name: service
